# Перетворення матриці A в верхню трикутну матрицю

![](C:\Users\User\A.png)

![Alt text](A.png)

In [27]:
import numpy as np
A = np.array([[4, 2, 0],
                 [1, 3, 2],
                 [-1, 3, 10]])
print(A)

[[ 4  2  0]
 [ 1  3  2]
 [-1  3 10]]


1. Змінюємо перший та другий рядки місцями.

![Alt text](A1.png)

In [5]:
A1 = np.array([A[1], A[0], A[2]])
print(A1)

[[ 1  3  2]
 [ 4  2  0]
 [-1  3 10]]


2. До 2-го рядка додати 1-ий, помножений на -4, до 3-го рядка додаємо 1-ий.

![Alt text](A2.png)

In [15]:
A2 = np.array([A1[0], A1[1] + A1[0]*(-4), A1[2] + A1[0]])
print(A2)

[[  1   3   2]
 [  0 -10  -8]
 [  0   6  12]]


3. 2-ий рядок ділимо на -2, 3-ій рядок ділимо на 6.

![Alt text](A3.png)

In [18]:
A3 = np.array([A2[0], A2[1]/(-2), A2[2]/6], dtype=int)
print(A3)

[[1 3 2]
 [0 5 4]
 [0 1 2]]


4. Змінюємо 2-ий та 3-й рядки місцями.

![Alt text](A4.png)

In [21]:
A4 = np.array([A3[0], A3[2], A3[1]])
print(A4)

[[1 3 2]
 [0 1 2]
 [0 5 4]]


5. До 3-го рядка додаємо 2-ий, помножений на -5. Отримуємо верхню трикутну матрицю.

![Alt text](A5.png "Верхня трикутна матриця")

In [28]:
A5 = np.array([A4[0], A4[1], A4[2] + A4[1]*(-5)])
print(A5)

[[ 1  3  2]
 [ 0  1  2]
 [ 0  0 -6]]
